### ISSUE TITLE
Napoleon attribution is incorrect

### ISSUE THREAD

**Issue by GLMeece** [Droogans/unmaintainable-code#34] opened 2018-08-17 13:53 UTC
Please read [the Wiki article on Hanlon's razor](https://en.wikipedia.org/wiki/Hanlon%27s_razor). This quote has been consistently misattributed, although I must admit this is the first time _I_ personally have seen it attributed to Napoleon.

**Comment by Droogans** [comment] 2018-08-20 15:00
Thank you for bringing this up! However, I am closing this as a duplicate of #29.

**Closed as completed by Droogans** 2018-08-20 15:00 UTC
